name: shell Commands
#it represents on which event workflows need to run
on: [push]

jobs:
  run-shell-commands:
  # on whjich OS we need to run the job.
    runs-on: ubuntu-latest  
    steps:
      - name: eccho a string
        run: echo "Hello World"
      - name: Multiple Scripts
      # Here | will use to run the multiple shell commands.
        run: |
          node -v
          npm -v 